server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rfruelu/SpringcloudConfig
          searchPaths: respo
      label: master
eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

