spring:
  datasource:
    #url: jdbc:mysql://10.79.1.224:3306/csmbp?useUnicode=true;characterEncoding=utf-8;autoReconnect=true;zeroDateTimeBehavior=convertToNull
    url: jdbc:mysql://10.79.1.224:3306/csmbp?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: user*2018
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    #配置监控统计拦截的filters
      filters: stat,wall,log4j
    #最大活跃数
      max-active: 20
     #初始化大小
      initial-size: 1
      #连接最大等待时间
      max-wait: 60000
      #打开prepared-statements cache
      pool-prepared-statements: true
    #指定每个连接prepared-statements cache 的大小
      max-pool-prepared-statement-per-connection-size: 20
      #通过connectionProperties属性打开mergeSql功能，慢sql记录，
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #database-platform: org.hibernate.dialect.MySQL5Dialect
# spring mvc 配置
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    host: 10.79.2.22
    port: 6379
    password: Csmbp2018
    pool:
      max-active: 50
      max-idle: 50
      min-idle: 10
      max-wait: 15000
    database: 0

#配置不打印日志的包
logging:
  level:
    com.lujia.denyLogger: 'off'
