eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}/${server.port}/eureka/
  instance:
    hostname: ${spring.application.name}
spring:
  application:
    name: eureka-server
server:
  port: 8762

